#server

spring.application.name=run-game

#DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/youngk8251?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
spring.datasource.username=youngk8251
spring.datasource.password=a1107225!

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

# Logging (???)
logging.level.org.hibernate.SQL=info
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=off
logging.level.com.example.rungame=info

# JWT
jwt.secret=7mQv!2ZpL8#sR1xN0aDk9@fG3hJ6wTyu
jwt.issuer=run-game
jwt.access-valid-seconds=900
jwt.refresh-valid-seconds=1209600